name: salami

packages:
  - "*"
  - packages/**

scripts:
  M:
    description: Merge all packages coverage tracefiles ignoring data related to generated files.
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info &&
      melos exec flutter test --coverage --test-randomize-ordering-seed random &&
      melos exec --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart &&
      coverde report -o coverage/html --high 100 -l -i coverage/filtered.lcov.info
      