name: salami
description: Complete Flutter template
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.2
  salami_api:
    path: packages/salami_api
  salami_repository:
    path: packages/salami_repository
  salami_theme:
    path: packages/salami_theme

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
