name: app_api
description: A Dart API Client for the App API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  json_annotation: ^4.4.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.1.0
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  test: ^1.20.1
  very_good_analysis: ^2.4.0
