name: salami

on: [pull_request, push]

jobs:
  build:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use local ci actions
        uses: ./.github/workflows/main_workflow
        with:
          flutter_channel: stable
          flutter_version: 2.10.3
